### ISSUE TITLE
火狐插件下载按钮点击无效

### ISSUE THREAD

**Issue by Tuskumo** [leoding86/pixiv-omina#12]
火狐版本：74.0b8 
插件版本:v3.9.0
情况如下：
页面正常弹出和显示插件按钮，点击下载键没有反应也没有执行下载操作，点击pixiv omina却弹出协议未与任何程序关联，确认了本机安装了pixiv omina，python2.7.15 和nodejs安装npm，
但是同主机下的谷歌浏览器的插件运行情况一切正常，版本同样是3.9.0

**Comment by leoding86** [comment]
可以试试 #27 中 panteras81 的解决办法。
