### ISSUE TITLE
希望修改保存名的时候可以不用非要以%id%开头

### ISSUE THREAD

**Issue by wearshoes** [leoding86/pixiv-omina#19]
设置里重命名的帮助里并没有写清楚保存名必须以%id%开头才行 尝试了好久才发现这个规律 希望能拿掉这层判断 不想保存图片的时候还要以id为开头保存

**Comment by leoding86** [comment]
你是说的哪个重命名规则？是图片的规则还是文件夹的规则？

**Comment by wearshoes** [comment]
应该是两个都是这样强制要求的吧

**Comment by leoding86** [comment]
我可以尝试取消掉必须有id的强制规则，不过要想一下在那加一个警告提示。

**Comment by leoding86** [comment]
Duplicate of #9

**Comment by wearshoes** [comment]
警告什么呢

**Comment by leoding86** [comment]
有些作者会将作品的名称设置成一样的，如果重命名的时候只使用作品名字，这样可能会导致下载会被覆盖或跳过。

**Comment by wearshoes** [comment]
那么是否可以通过使用 作者名/作品名/作品序号 这种路径作为唯一值规避这个问题呢 作品序号指某个漫画10张图 序号为0-9 单图为 1

**Comment by leoding86** [comment]
这个我会考虑一下

**Comment by leoding86** [comment]
版本0.5.0修改了重命名逻辑，可以升级以后尝试一下。

**Comment by wearshoes** [comment]
> 版本0.5.0修改了重命名逻辑，可以升级以后尝试一下。

好的多谢
