### ISSUE TITLE
请问一下，插件更新历史说添加了fanbox支持，但是在fanbox中并没有看到下载按钮？

### ISSUE THREAD

**Issue by sakurairsora** [leoding86/pixiv-omina#25]
请问应该如何下载fanbox中的内容？fanbox的浏览也并没有浏览记录

**Comment by leoding86** [comment]
我应该没有说过会在这个应用中支持fanbox，倒是Pixiv Toolkit插件中是支持的，不过首先你得有权限查看作品，并不能在不订阅作者的情况下免费下载内容。
