### ISSUE TITLE
Error:There is nothing showing on the login window!

### ISSUE THREAD

**Issue by Ziffer-yan** [leoding86/pixiv-omina#3]
![image](https://user-images.githubusercontent.com/33079825/71473697-1335bd00-2813-11ea-9222-469686c0ce8e.png)

**Comment by leoding86** [comment]
Can you visit Pixiv without a proxy? If you cannot, you should use set a proxy in settings.

**Comment by Ziffer-yan** [comment]
> Can you visit Pixiv without a proxy? If you cannot, you should use set a proxy in settings.

yeah, after set the proxy as http://127.0.0.1:1080 , I can log in on the pixiv site. Much Thanks!!! 👍
