### ISSUE TITLE
Wrong link in the download entry

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/pixiv-omina#32]
The download entries have the wrong URL.
For example, the click on it opens `https://www.pixiv.net/artworks/pixiv:84413732` (404), but should `https://www.pixiv.net/artworks/84413732`.

**Comment by leoding86** [comment]
Fixed after commit [23107bc](https://github.com/leoding86/pixiv-omina/commit/23107bc71f6fb243dea6f41a0cc136884568a1f2)
