### ISSUE TITLE
I can't download bulk picture in new version

### ISSUE THREAD

**Issue by dawnte** [leoding86/pixiv-omina#35]
After I download a new version. I can't download picture with bulk/pages. they only get downloaded at the first page and the next page/bulk won't get downloaded and the process is complete

**Comment by leoding86** [comment]
Could you provide your renaming settings? I guess the rename settings miss %page_num% part.

**Comment by dawnte** [comment]
Hello thanks for solution. My problem is solved.      
![1](https://user-images.githubusercontent.com/71814101/94389474-2a2a8680-017a-11eb-8013-925fb6e94472.PNG)
![2](https://user-images.githubusercontent.com/71814101/94389485-2f87d100-017a-11eb-85b5-c06c91b746a7.PNG)
