### ISSUE TITLE
[Feature Request] Download specific page of the artist's profile

### ISSUE THREAD

**Issue by sakkamade** [leoding86/pixiv-omina#40]
Hello.

If that's possible I'd like to have such a position in `Pixiv Omina`.

For example:  if I'll paste url `https://www.pixiv.net/en/users/*****/artworks?p=2` into the `Add download` window,
the `Pixiv Omina` will download only a second page of the author, or only manga etc.

**Comment by leoding86** [comment]
It's hard to track the pagination logic because Pixiv can easily change it which will cause the application parse the wrong artworks. So the answer is no.
