### ISSUE TITLE
There are some thing unreasonable

### ISSUE THREAD

**Issue by bluesatan0-0** [leoding86/pixiv-omina#44]
I  selected all finished tasks with Ctrl+A in the finshed tasks list, and clicked the deleted icon, it delete the tasks which haven`t finished and even haven`t started. 

![image](https://user-images.githubusercontent.com/29154434/99653827-7ddb9100-2a94-11eb-92f2-f0df10cd77eb.png)

**Comment by leoding86** [comment]
Issue confirmed.

**Comment by leoding86** [comment]
Fixed in latest version. Sorry for later reply.
