### ISSUE TITLE
setup missing in 0.5.1 download

### ISSUE THREAD

**Issue by Ventuquies** [leoding86/pixiv-omina#46]
Setup.exe is missing in 0.5.1 Assets do download :-( Does anybody know how to compile it correctly on a win 10 machine? Thanks!

**Comment by Ventuquies** [comment]
I was able to compile and create the setup 👍 
see instructions https://www.liquidweb.com/kb/how-to-install-yarn-on-windows/#:~:text=%20Yarn%20Installation%20%201%20MSI%20Installation.%20The,the%20Scoop%20command%20line%20installer%20for...%20More%20
1.) download and install Node.js https://nodejs.org/en/download/
2.) download and install yarn https://classic.yarnpkg.com/en/docs/install#windows-stable
3.) follow instructions on site to create setup.exe / start with yarn :-)

Thank you so much developer leoding86!! When I find out how to donate to you I will!

**Comment by leoding86** [comment]
Sorry. I forgot to upload the binary. Now it is in the assets.
