### ISSUE TITLE
How to stop the app from downloading pictures in separate folders

### ISSUE THREAD

**Issue by Lucatiel26** [leoding86/pixiv-omina#48]
I would like to know how to change the option to not having each picture downloaded in its own folder, rather I would like it to just get downloaded in 1 folder along with other pictures. Thank you

**Comment by leoding86** [comment]
Do you mean save downloaded images to one single folder even if there are multiple images in a single work?

**Comment by Lucatiel26** [comment]
Yes that too, but mostly I would like to have pictures I download to not get packed in their own separate folder. Like it was in the older version.

**Comment by leoding86** [comment]
@Lucatiel26 The issue has been fixed in the source code, and the function will be fixed when the next version is released.

**Comment by Lucatiel26** [comment]
Not sure if I was being clear. Sorry about that, but I meant that I wish for **single** pictures to not get saved in their custom folder, but rather just get downloaded directly to my relative location.

This issue also seems to occur.
> Do you mean save downloaded images to one single folder even if there are multiple images in a single work?

It would also be nice if pictures would just be saved in the **relative folder** without any subfolders to separate them. I think there used to be an option like that in the older version.

**Comment by leoding86** [comment]
I just release version 0.7.5. Please read `About Rename settings` section before you update.
