### ISSUE TITLE
点击“登录pixiv”无效

### ISSUE THREAD

**Issue by reed0214** [leoding86/pixiv-omina#51]
![1](https://user-images.githubusercontent.com/13160124/103215257-cd439580-494d-11eb-8e60-2d9d5b9092db.gif)
你好，请问下，我点击登录按钮，但是没有弹出登录界面，这个是什么问题呢，我修改了防火墙依旧不行，谢谢
Pixiv Omina Version: 0.7.0
Operating System: Windows 10 Pro x64 20H2

**Comment by leoding86** [comment]
你确定可以在不用VPN的情况下访问P站吗？

**Comment by reed0214** [comment]
我在大陆,不用vpn是没办法直连的,目前pc用的V2rayN全局模式,正常情况下,所有软件只要是域名设置过代理模式,都会走代理,所以正常情况pixiv-omina请求网路链接的话,应该是可以正常走代理的吧,但是现在的情况好像是pixiv-omina没走代理,v2rayn的日志里面也没看到相关域名通过的记录,所以现在是不知道怎么处理了.
PS:我试了两台电脑,都是通过V2rayN走代理,都是一样的情况,没出现登录页面

**Comment by reed0214** [comment]
而且现在还有个很无语的问题,我是这用chrome浏览https://raw.githubusercontent.com/leoding86/pixiv-omina/master/package.json,登录成功后几秒后文本就全部消息了,不知道会不会和这个也有关系
chrome版本 87.0.4280.88（正式版本） （64 位）

**Comment by leoding86** [comment]
并不是所有软件都可以走代理，可以走代理的软件是应用了系统的代理设置。据我所知，electron应用目前应该没有可以读取系统代理设置的办法，所以需要在代理设置里面自己设置。

**Comment by reed0214** [comment]
嗯嗯，那好的，谢谢了，我再去试试

**Comment by leoding86** [comment]
先关闭了，有问题可以再开。
