### ISSUE TITLE
Pixiv Comic %numbering_title%

### ISSUE THREAD

**Issue by sakkamade** [leoding86/pixiv-omina#53]
#### Version

Omina 0.7.5 

#### What's the problem

Wrong string within `Settings > Help` under `Pixiv Comic usable rename placeholders:`.
In case if I write `%numbering-title%` as it suggests, in the file/folder name I'll see word "undefined". Whereas if I write `%number-title%` the file/folder name will be displaying properly.

**Comment by leoding86** [comment]
Maybe Pixiv change the property. I'll investigate it later.

**Comment by leoding86** [comment]
The help information is incorrect. I'll fix it in next version.
