### ISSUE TITLE
下载界面时的选项可否记忆.

### ISSUE THREAD

**Issue by aq82997289** [leoding86/pixiv-omina#54]
动图、插图、漫画，这3个选项，如果可以单独设置开/关，或者软件关闭之前，能一直记忆就好了。
每一次输入作者主页时，都要再点2下，以取消勾选 动图、漫画 ，多少有一点”不太效率“ 。

其实区别不大，但~优化嘛~ 总得有人提出点奇怪的小细节。
再次感谢作者的作品，利器！

**Comment by leoding86** [comment]
我会考虑下一个版本中在对话框中添加一个"记住"选项。
