### ISSUE TITLE
Cannot read property 'illustration','manga' of undefined

### ISSUE THREAD

**Issue by sakkamade** [leoding86/pixiv-omina#55]
**Omina Version**

0.7.5

**What's the problem**

Clicking the `Omina` button in browser before the page being loaded  results in `Cannot read property 'illustration' of undefined`.
And after such error, even if I reload the page properly and click the button again, or manually parse the link, `Pixiv Omina` would not download artwork until the errored item will be deleted from `Pixiv Omina` (red trash bin button).

![Screenshot-omina-error](https://user-images.githubusercontent.com/62730422/103397442-773b4180-4b49-11eb-806e-a64b5982642a.png)

**Extra info**

Browser (`Firefox`) showed such error page in previous versions as well, however `Pixiv Omina` downloaded the image without any issues.

**Comment by leoding86** [comment]
Issue has been located. Fix it in next version.

**Comment by sakkamade** [comment]
@leoding86 , I'll ask just to make sure. The links for manga doesn't work, at all. Is that fixed as well?

_Update:_
Error looks similar - `Cannot read property 'manga' of undefined`, but in this case it appears to be impossible to download it.

**Comment by leoding86** [comment]
@sakkamade I just fix it in source code. So you need to wait binary release for using 'Omina' button in browser.

**Comment by sakkamade** [comment]
@leoding86 Yeah, I understand that. But, the **manga** doesn't downloading even via parsing a link into `Pixiv Omina`. There's completely no way to download **manga**, at least for me. So I was wondering if that another, unrelated issue.

**Comment by leoding86** [comment]
Issue confirmed. It's a related issue, I'll release a new version asap.

**Comment by sakkamade** [comment]
Well, it **is** urelated, since it wasn't as yet fixed .

**Comment by leoding86** [comment]
Try version 0.7.6. The issues have been fixed, I think.

**Comment by sakkamade** [comment]
Either way, `0.7.6` seemed to fix everything. Closing it.

@leoding86 , Yes, they were.
