### ISSUE TITLE
gif图片的命名规则中包含页码，而实际名称不含页码，应该缺省字段，但实际是undefined

### ISSUE THREAD

**Issue by bluesatan0-0** [leoding86/pixiv-omina#61]
![image](https://user-images.githubusercontent.com/29154434/111084462-73ff0180-854d-11eb-9c18-57a2885a5b75.png)

**Comment by leoding86** [comment]
现在默认设置里面应该是没有页码规则的，如果有的话，把页码规则去掉应该就可以了。
