### ISSUE TITLE
添加收藏夹任务时报错。

### ISSUE THREAD

**Issue by bluesatan0-0** [leoding86/pixiv-omina#62]
![image](https://user-images.githubusercontent.com/29154434/111885325-0f86eb00-8a02-11eb-9085-608c15cb8465.png)
![image](https://user-images.githubusercontent.com/29154434/111885327-1281db80-8a02-11eb-80cc-a9d4ec7104ba.png)

**Comment by Cidenia** [comment]
同样问题+1

**Comment by leoding86** [comment]
目前的版本没有日志模块不太好追踪问题。这两天应该会更新一个版本，会添加一些功能，其中包括日志模块，到时候再看看。

**Comment by leoding86** [comment]
最新版下载应该没有问题了。关闭。

**Comment by leoding86** [comment]
最新版下载应该没有问题了。关闭。
