### ISSUE TITLE
功能建议：下载至的文件夹重命名

### ISSUE THREAD

**Issue by chencl0214** [leoding86/pixiv-omina#65]
以画师链接下载画师所有作品时，所有文件保存至一个可以自定义重命名的文件夹，类似默认为“%画师id%_%画师名%”

**Comment by leoding86** [comment]
可以直接设置三个作品类型的重命名为 %user_id%_%user_name%/[其他参数]

**Comment by chencl0214** [comment]
> 可以直接设置三个作品类型的重命名为 %user_id%_%user_name%/[其他参数]

我的意思是直接下载一个画师所有作品的时候，下载的东西是以文件夹的形式放在download的路径下，我是想直接让这个画师所有的作品放到以这个画师的名字为名的文件夹下。

**Comment by bluesatan0-0** [comment]
> > 可以直接设置三个作品类型的重命名为 %user_id%_%user_name%/[其他参数]
> 
> 我的意思是直接下载一个画师所有作品的时候，下载的东西是以文件夹的形式放在download的路径下，我是想直接让这个画师所有的作品放到以这个画师的名字为名的文件夹下。

现有的重命名规则是支持这种设置的，你自己多看看

**Comment by bluesatan0-0** [comment]
> > 可以直接设置三个作品类型的重命名为 %user_id%_%user_name%/[其他参数]
> 
> 我的意思是直接下载一个画师所有作品的时候，下载的东西是以文件夹的形式放在download的路径下，我是想直接让这个画师所有的作品放到以这个画师的名字为名的文件夹下。

现有的重命名规则是支持这种设置的，你自己多看看。这是我的设置：
%user_id%_%user_name%/%title%/%id%_%title%_%page_num%

**Comment by bluesatan0-0** [comment]
> > 可以直接设置三个作品类型的重命名为 %user_id%_%user_name%/[其他参数]
> 
> 我的意思是直接下载一个画师所有作品的时候，下载的东西是以文件夹的形式放在download的路径下，我是想直接让这个画师所有的作品放到以这个画师的名字为名的文件夹下。

现有的重命名规则是支持这种设置的，你自己多看看。这是我的设置：
%user_id%_%user_name%/%title%/%id%_%title%_%page_num%

**Comment by leoding86** [comment]
@chencl0214 我明白你的意思，但是那需要在程序中硬编码重命名设置，再没有比较好的方案前暂时不会实现这个。我会暂时保持这个issue是open状态，如果有比较好的方案可以提出来。
