### ISSUE TITLE
No distinction by colour

### ISSUE THREAD

**Issue by sakkamade** [leoding86/pixiv-omina#69]
**Omina Version**
~0.8.0

**What's the problem**
It used to be amazing to have `Manga`, `Illustration`, etc. of a distinct colours, whereas now:

![Screenshot](https://user-images.githubusercontent.com/62730422/112738382-6d638780-8f5a-11eb-9a59-89576253a99f.png)

**Post scriptum**
All in blues gives me blues...

**Comment by sakkamade** [comment]
Also, I do not quite understand significance of the word "Pixiv" before its category.
Shouldn't it be plain even without it?

I suggest to remove it.

**Comment by JazzXin** [comment]
the artwork I download registers as manga too not just the color

**Comment by sakkamade** [comment]
@JazzXin Well, yes, because I built it from current master. That is why I mentioned `~0.8.0`. The fix is not present in `0.8.0` release. Here is the issue https://github.com/leoding86/pixiv-omina/issues/67.

Nevertheless, I am using `~0.7.7`(couple commits after release) presently, until/if this will be fixed. For it might have been intended change. 
Although changing it back might be a couple lines, I have no intention of doing it for now. (^^ゞ

**Comment by JazzXin** [comment]
@sakkamade Sorry, I don't use github often besides downloading releases so checking closed issues didn't come to my mind. I'm currently content with using version `0.7.7`. If I find any issues with it, I'll change to the version `~0.7.7` or `~0.8.0` that you mentioned. Thanks for clarifying it for me. 

Also I totally agree with your take. All tags being blue is not a good choice if it is intended.

**Comment by sakkamade** [comment]
> If I find any issues with it, I'll change to the version ~0.7.7

You don't have to worry about it, for, as far as I remember, 
there was no particular issues with 0.7.7 `.exe` release, 
the problem is within its `.tar.gz` and `.zip` variations.

Nevertheless, we shouldn't stick with old versions if we are able to correct,
 point out the issues, and improve newer software.
Well, of course, the main words are the ones of maintainer.

**Comment by sakkamade** [comment]
I guess this was fixed with https://github.com/leoding86/pixiv-omina/commit/7d8cd8dc76c979c0ed0fcd7e37429e805d90293a, however I cannot check it now.  Closing.

P.s. 

https://github.com/leoding86/pixiv-omina/blob/7d8cd8dc76c979c0ed0fcd7e37429e805d90293a/src/main/modules/Downloader/WorkDownloader/Pixiv/NovelDownloader.js#L40

Should not this be be  `this.tagColor`?
