### ISSUE TITLE
我无法一键下载作者的所有作品

### ISSUE THREAD

**Issue by 199548zyc** [leoding86/pixiv-omina#8]
将作者主页链接张贴到下载链接后提示无效链接。
![QQ截图20200220033012](https://user-images.githubusercontent.com/61249567/74868548-651d3e00-5391-11ea-91d3-bf7a06171725.png)

**Comment by leoding86** [comment]
作者页面有两种类型的链接，目前没有做兼容。
不能工作：https://www.pixiv.net/en/users/数字
可以工作：https://www.pixiv.net/member.php?id=数字 

现在用的机器开发环境有问题，暂时解决不了。

**Comment by leoding86** [comment]
Duplicate of #6

**Comment by 199548zyc** [comment]
谢谢解决
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leoding86"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上7:15
收件人: "leoding86/pixiv-omina"<pixiv-omina@noreply.github.com&gt;; 
抄送: "熊猫"<996571979@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [leoding86/pixiv-omina] 我无法一键下载作者的所有作品 (#8)




作者页面有两种类型的链接，目前没有做兼容。
 不能工作：https://www.pixiv.net/en/users/数字
 可以工作：https://www.pixiv.net/member.php?id=数字
 
现在用的机器开发环境有问题，暂时解决不了。
