### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by zhongfly** [leoding86/pixiv-omina#80]
已设置代理，且确保可用
下载链接 https://comic.pixiv.net/works/6513
下载comic报错如下：
![Snipaste_2021-07-04_12-15-50](https://user-images.githubusercontent.com/11155705/124373071-f577cc80-dcc1-11eb-87c4-4ca2a045c311.png)
![image](https://user-images.githubusercontent.com/11155705/124373097-20622080-dcc2-11eb-899d-4b21fdc0bba2.png)

**Comment by leoding86** [comment]
可能页面改了规则，我晚些时候看一下。

**Comment by leoding86** [comment]
已在 https://github.com/leoding86/pixiv-omina/commit/f203f826dfc3e7fd1838ae66db8e38625aa86f3e 中修复。 晚些时候更新。
