### ISSUE TITLE
[Feature Request]下载Pixiv Comic时可只下载需要的

### ISSUE THREAD

**Issue by zhongfly** [leoding86/pixiv-omina#81]
希望能够自由选择要下载的内容，而不是默认全部下载

**Comment by sakkamade** [comment]
You mean to download only certain pictures of certain chapter of the work? 
Or do you mean to download only certain chapters, and not the entire work?

If only chapters, you already can. Just paste the link of the chapter instead of the link of the work.

**Comment by zhongfly** [comment]
> You mean to download only certain pictures of certain chapter of the work?
> Or do you mean to download only certain chapters, and not the entire work?
> 
> If only chapters, you already can. Just paste the link of the chapter instead of the link of the work.

Thanks,I see.
