### ISSUE TITLE
Return undetermined class to undetermined item

### ISSUE THREAD

**Issue by sakkamade** [leoding86/pixiv-omina#82]
Since you don't seem to accept PRs much, here is the description of the issue I see:

Undetermined class
https://github.com/leoding86/pixiv-omina/blob/4c9bd66761dbabc64a9b0a042853737ba1dd44df/src/renderer/components/DownloadList.vue#L269
is no longer used, there is no undetermined class in the item any more.

And the background colour which  takes "undetermined" item's tag is from this class
https://github.com/leoding86/pixiv-omina/blob/4c9bd66761dbabc64a9b0a042853737ba1dd44df/src/renderer/components/DownloadList.vue#L256-L258

---

My suggestions are to change the background colour of `.download-list-item__tag` and remove `.download-list-item--undetermined` class, or return undetermined class to the item.

**Comment by sakkamade** [comment]
The same with Pixiv Comic item, but here the solution is  more straightforward.

Since the name for Pixiv Comic item has been changed to Pixiv Comic Episode, the class should be renamed to corresponding.

**Comment by leoding86** [comment]
related to commit 81932874e42a57316fe7879f408d6013884db8d0

**Comment by sakkamade** [comment]
Thank you!
