### ISSUE TITLE
[Feature Request] Additional placeholder for Pixiv Comic

### ISSUE THREAD

**Issue by sakkamade** [leoding86/pixiv-omina#83]
**What is the request**
Since Pixiv Comic not only assigns its own ids to the works, but also to each separate chapter, e.g. `https://comic.pixiv.net/viewer/stories/**12345**`, I would like to have the placeholder for this as well :heart: 

EDIT: Placing the `%id%` to filename results in "undefined."

**Comment by leoding86** [comment]
related wrong commit, should be #82

**Comment by sakkamade** [comment]
Thank you!
