### ISSUE TITLE
无法更改文件默认保存位置请问如何解决

### ISSUE THREAD

**Issue by qq793243811** [leoding86/pixiv-omina#89]
https://imgtu.com/i/fTLort
如图

**Comment by qq793243811** [comment]
顺便再问一下如果保存的画师更新了图片再下载的话是会覆盖源文件吗

**Comment by sakkamade** [comment]
> https://imgtu.com/i/fTLort
如图

I'm having exactly the same problem. 
I thought it was something wrong with my setup...

What version of Pixiv Omina are you using?

As a temporary workaround I changed the path in the config file. 
In my case, the config was in `/home/user/.config/Pixiv Omina/config/settings.config` (I am on Linux).

Default path can be changed here:
```json
{"saveTo":"/default/path", ...}
```

**Comment by qq793243811** [comment]
> > https://imgtu.com/i/fTLort
> > 就像
> 
> 我遇到了完全相同的问题。
> 我还以为是我的设置有问题...
> 
> 您使用的是哪个版本的 Pixiv Omina？
> 
> 作为临时解决方法，我更改了配置文件中的路径。
> 就我而言，配置在`/home/user/.config/Pixiv Omina/config/settings.config`（我在 Linux 上）。
> 
> 可以在此处更改默认路径：
> 
> ```json
> { " saveTo " : " /default/path " , ... }
> ```

{"saveTo":"/default/path", ...}My system is win10. There is no such file in the config folder

**Comment by sakkamade** [comment]
@qq793243811, Did you resolve the problem?

> {"saveTo":"/default/path", ...}My system is win10. There is no such file in the config folder

Do you use a single-user mode? If so, the config file is located somewhere in the folder together with `.exe` executable. 
Look in installation directory.

If you don't use a single-user mode, just try to search for `settings.config` file or `Pixiv Omina` directory in 
e.g. `C:\Users\(username)\AppData\Local` or `C:\Users\(username)\AppData\Roaming`
